In [27]:
import pandas as pd

melb_df = pd.read_csv('data/melb_data_ps.csv')
melb_df.head()

,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Coordinates
0,0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,...,1,202.0,126.0,1970,Yarra,-37.7996,144.9984,Northern Metropolitan,4019,"-37.7996, 144.9984"
1,1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,...,0,156.0,79.0,1900,Yarra,-37.8079,144.9934,Northern Metropolitan,4019,"-37.8079, 144.9934"
2,2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,...,0,134.0,150.0,1900,Yarra,-37.8093,144.9944,Northern Metropolitan,4019,"-37.8093, 144.9944"
3,3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,...,1,94.0,126.0,1970,Yarra,-37.7969,144.9969,Northern Metropolitan,4019,"-37.7969, 144.9969"
4,4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,...,2,120.0,142.0,2014,Yarra,-37.8072,144.9941,Northern Metropolitan,4019,"-37.8072, 144.9941"

In [16]:
display(melb_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          13580 non-null  int64
 1   Suburb         13580 non-null  object
 2   Address        13580 non-null  object
 3   Rooms          13580 non-null  int64
 4   Type           13580 non-null  object
 5   Price          13580 non-null  float64
 6   Method         13580 non-null  object
 7   SellerG        13580 non-null  object
 8   Date           13580 non-null  object
 9   Distance       13580 non-null  float64
 10  Postcode       13580 non-null  int64
 11  Bedroom        13580 non-null  int64
 12  Bathroom       13580 non-null  int64
 13  Car            13580 non-null  int64
 14  Landsize       13580 non-null  float64
 15  BuildingArea   13580 non-null  float64
 16  YearBuilt      13580 non-null  int64
 17  CouncilArea    12211 non-null  object
 18  Lattitude      13580 non-null  float64
 19  Longtitude     13580 non-null  float64
 20  Regionname     13580 non-null  object
 21  Propertycount  13580 non-null  int64
 22  Coordinates    13580 non-null  object
dtypes: float64(6), int64(8), object(9)
memory usage: 2.4+ MB

None

In [18]:
melb_df.sort_values(by='Price').head(10)

,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Coordinates
2652,2652,Footscray,202/51 Gordon St,1,u,85000.0,PI,Burnham,3/09/2016,6.4,...,0,0.0,126.0,2007,Maribyrnong,-37.79110,144.89000,Western Metropolitan,7570,"-37.7911, 144.89"
1805,1805,Caulfield,30 Pyne St,4,h,131000.0,PI,Rodney,25/02/2017,8.9,...,2,499.0,155.0,1920,Glen Eira,-37.88640,145.02420,Southern Metropolitan,2379,"-37.8864, 145.0242"
7303,7303,Albion,8/6 Ridley St,1,u,145000.0,PI,Biggin,28/05/2016,13.9,...,1,36.0,126.0,1970,Brimbank,-37.78330,144.82660,Western Metropolitan,2185,"-37.7833, 144.8266"
1927,1927,Coburg,171 Moreland Rd,4,h,145000.0,PI,Jellis,4/06/2016,7.8,...,1,536.0,164.0,1910,Moreland,-37.75550,144.96580,Northern Metropolitan,11204,"-37.7555, 144.9658"
7940,7940,Hawthorn,17/17 Park St,1,u,160000.0,VB,HAR,8/04/2017,4.6,...,0,322.0,126.0,2009,Boroondara,-37.81980,145.03730,Southern Metropolitan,11308,"-37.8198, 145.0373"
12666,12666,Brunswick,4/831 Park St,1,u,170000.0,VB,Nelson,16/09/2017,5.2,...,0,1250.0,126.0,1970,NaN,-37.77685,144.95188,Northern Metropolitan,11918,"-37.77685, 144.95188"
8811,8811,Footscray,10/30 Pickett St,1,u,170000.0,PI,Burnham,1/07/2017,5.1,...,0,30.0,26.0,2013,Maribyrnong,-37.80141,144.89587,Western Metropolitan,7570,"-37.80141, 144.89587"
8504,8504,West Footscray,8/132 Rupert St,1,u,185000.0,PI,Jas,29/04/2017,8.2,...,1,0.0,126.0,1970,Maribyrnong,-37.79800,144.86720,Western Metropolitan,5058,"-37.798, 144.8672"
7293,7293,Albion,10/117 Anderson Rd,1,u,185000.0,S,hockingstuart,22/08/2016,13.9,...,1,2347.0,43.0,1975,Brimbank,-37.78520,144.82720,Western Metropolitan,2185,"-37.7852, 144.8272"
7305,7305,Albion,5/25 Ridley St,2,u,190000.0,SP,Burnham,30/07/2016,13.9,...,1,0.0,126.0,1970,Brimbank,-37.78390,144.82390,Western Metropolitan,2185,"-37.7839, 144.8239"

In [19]:
melb_df.sort_values(by='Date', ascending=False)

,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Coordinates
12497,12497,Fitzroy,101 Kerr St,3,h,1750000.0,VB,Jellis,9/09/2017,2.1,...,2,152.0,126.00,1970,NaN,-37.79662,144.97910,Northern Metropolitan,5825,"-37.79662, 144.9791"
12555,12555,Mentone,14A Teague Av,3,t,875000.0,S,hockingstuart,9/09/2017,20.0,...,2,165.0,19.00,1970,NaN,-37.97904,145.06385,South-Eastern Metropolitan,6162,"-37.97904, 145.06385"
12543,12543,Kew East,29 Elm Gr,3,h,1655000.0,SA,RT,9/09/2017,7.3,...,1,822.0,126.00,1970,NaN,-37.78896,145.04728,Southern Metropolitan,2671,"-37.78896, 145.04728"
12542,12542,Kew East,11 Coleman Av,4,h,2000000.0,VB,Marshall,9/09/2017,7.3,...,1,704.0,126.00,1970,NaN,-37.79349,145.04611,Southern Metropolitan,2671,"-37.79349, 145.04611"
12541,12541,Kew East,38 Bennett Pde,3,h,1700000.0,S,hockingstuart,9/09/2017,7.3,...,2,579.0,126.00,1970,NaN,-37.79733,145.06047,Southern Metropolitan,2671,"-37.79733, 145.06047"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8957,8957,Sunbury,11 Bannermann St,4,h,580000.0,S,Raine,1/07/2017,31.7,...,2,613.0,221.00,2011,Hume,-37.59501,144.70069,Western Metropolitan,14092,"-37.59501, 144.70069"
8956,8956,Strathmore,2/30 Bulla Rd,2,h,646000.0,S,Nelson,1/07/2017,8.2,...,1,184.0,126.00,1990,Moonee Valley,-37.74040,144.90835,Western Metropolitan,3284,"-37.7404, 144.90835"
8830,8830,Hawthorn,7/28 Elm St,1,u,395000.0,S,Peter,1/07/2017,5.3,...,1,910.0,126.00,1970,Boroondara,-37.81333,145.01932,Southern Metropolitan,11308,"-37.81333, 145.01932"
8831,8831,Hawthorn,1/514 Glenferrie Rd,3,u,1000000.0,S,Jellis,1/07/2017,5.3,...,1,1079.0,90.00,1940,Boroondara,-37.82987,145.03421,Southern Metropolitan,11308,"-37.82987, 145.03421"
8793,8793,Donvale,1 Bernarra Ct,7,h,2705000.0,S,Ray,1/07/2017,16.1,...,4,5022.0,409.54,2004,Manningham,-37.76598,145.19329,Eastern Metropolitan,4790,"-37.76598, 145.19329"

In [20]:
melb_df.sort_values(by=['Distance', 'Price']).loc[::10, ['Distance', 'Price']]

       Distance      Price
11428       0.0   387000.0
10512       0.7   600000.0
5727        1.2   485000.0
8671        1.2   595000.0
5736        1.2   740000.0
...         ...        ...
12011      38.0   680000.0
10673      38.0   810000.0
13429      38.0  1155000.0
11102      41.0   650000.0
12728      45.9   650000.0

[1358 rows x 2 columns]

In [ ]:
# Загрузите именно этот файл, чтобы цифры совпали с тестом
basic_df = pd.read_csv('data/melb_data.csv') 
basic_df['Date'] = pd.to_datetime(basic_df['Date'], dayfirst=True)
print(basic_df['Date'].dt.quarter.value_counts())

In [2]:
import pandas as pd

# Загружаем файл
melb_df = pd.read_csv('data/melb_data_ps.csv')

# Важно: указываем dayfirst=True, чтобы формат был ДД/ММ/ГГГГ
melb_df['Date'] = pd.to_datetime(melb_df['Date'], dayfirst=True)

# Считаем кварталы
res = melb_df['Date'].dt.quarter.value_counts()
print(res)

Date
3    5377
2    4808
4    2272
1    1123
Name: count, dtype: int64

In [3]:
melb_df.groupby(by='Type').mean(numeric_only=True)

,index,Rooms,Price,Distance,Postcode,Bedroom,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
Type,,,,,,,,,,,,,,
h,7075.985924,3.260874,1.242665e+06,10.979479,3104.080643,3.229336,1.613822,1.772674,617.181924,152.162553,1960.889089,-37.803795,144.994700,7259.025505
t,6269.107720,2.837522,9.337351e+05,9.851346,3100.777379,2.814183,1.809695,1.555655,279.606822,134.649710,1989.828546,-37.815782,144.996489,7094.459605
u,6084.399403,1.963871,6.051275e+05,7.607391,3110.797481,1.966523,1.183295,1.128936,477.314219,102.235863,1976.756381,-37.823710,144.996363,8199.280080

In [4]:
melb_df.groupby('Type')['Price'].mean()

Type
h    1.242665e+06
t    9.337351e+05
u    6.051275e+05
Name: Price, dtype: float64

In [13]:
melb_df.groupby('Regionname')['Distance'].min().sort_values(ascending=False)

Regionname
Western Victoria              29.8
Eastern Victoria              25.2
Northern Victoria             21.8
South-Eastern Metropolitan    14.7
Eastern Metropolitan           7.8
Western Metropolitan           4.3
Southern Metropolitan          0.7
Northern Metropolitan          0.0
Name: Distance, dtype: float64

In [18]:
melb_df.groupby ('MonthSale')['Price'].agg(
    ['count', 'mean', 'max']
).sort_values(by='count', ascending=False)

KeyError: 'MonthSale'

In [21]:
melb_df.groupby('Regionname')['SellerG'].agg(
    		['nunique', set]
)

,nunique,set
Regionname,,
Eastern Metropolitan,70,"{Buckingham, Woodards, Lindellas, Assisi, Noel..."
Eastern Victoria,18,"{Eview, Ray, Harcourts, Morrison, McGrath, Pea..."
Northern Metropolitan,112,"{Nick, Woodards, Walshe, Pagan, Iconek, buyMyp..."
Northern Victoria,16,"{Buckingham, LITTLE, Reliance, hockingstuart, ..."
South-Eastern Metropolitan,52,"{Eview, Woodards, Veitch, U, Noel, Aquire, Bar..."
Southern Metropolitan,131,"{Nick, Woodards, Assisi, Walshe, buyMyplace, M..."
Western Metropolitan,92,"{Point, Woodards, Ace, Walshe, Pagan, Leeburn,..."
Western Victoria,9,"{Ray, hockingstuart, Reliance, YPA, PRDNationw..."

In [22]:
melb_df.groupby('Rooms')[['Price', 'BuildingArea']].median()

           Price  BuildingArea
Rooms
1       385000.0         107.0
2       690000.0         126.0
3       950000.0         126.0
4      1285000.0         142.0
5      1660000.0         176.0
6      1800000.0         126.0
7      1496000.0         216.5
8      1515000.0         126.0
10      900000.0         126.0

In [23]:
melb_df.groupby(['Rooms', 'Type'])['Price'].mean()

Rooms  Type
1      h       8.668655e+05
       t       5.927045e+05
       u       3.899289e+05
2      h       1.017238e+06
       t       7.101585e+05
       u       6.104905e+05
3      h       1.109233e+06
       t       9.847087e+05
       u       8.505963e+05
4      h       1.462283e+06
       t       1.217092e+06
       u       1.037476e+06
5      h       1.877327e+06
       t       1.035000e+06
6      h       1.869508e+06
       u       5.200000e+05
7      h       1.920700e+06
8      h       1.510286e+06
       u       2.250000e+06
10     h       9.000000e+05
Name: Price, dtype: float64

In [24]:
melb_df.groupby(['Rooms', 'Type'])['Price'].mean().unstack()

Type              h             t             u
Rooms
1      8.668655e+05  5.927045e+05  3.899289e+05
2      1.017238e+06  7.101585e+05  6.104905e+05
3      1.109233e+06  9.847087e+05  8.505963e+05
4      1.462283e+06  1.217092e+06  1.037476e+06
5      1.877327e+06  1.035000e+06           NaN
6      1.869508e+06           NaN  5.200000e+05
7      1.920700e+06           NaN           NaN
8      1.510286e+06           NaN  2.250000e+06
10     9.000000e+05           NaN           NaN

In [31]:
melb_df.pivot_table(
    values='Price',
    index='Rooms',
    columns='Type',
    fill_value=0
).round()

Type           h          t          u
Rooms
1       866866.0   592705.0   389929.0
2      1017238.0   710158.0   610491.0
3      1109233.0   984709.0   850596.0
4      1462283.0  1217092.0  1037476.0
5      1877327.0  1035000.0        0.0
6      1869508.0        0.0   520000.0
7      1920700.0        0.0        0.0
8      1510286.0        0.0  2250000.0
10      900000.0        0.0        0.0

In [32]:
melb_df.pivot_table(
    values='Price',
    index='Regionname',
    columns='Weekend',
    aggfunc='count'
)

KeyError: 'Weekend'

In [33]:
melb_df.pivot_table(
    values='Landsize',
    index='Regionname',
    columns='Type',
    aggfunc=['median', 'mean'],
    fill_value=0
)

                           median                       mean              \
Type                            h      t      u            h           t
Regionname
Eastern Metropolitan        674.0  233.5  203.0   717.422847  269.440678
Eastern Victoria            843.0    0.0  230.0  3108.960000    0.000000
Northern Metropolitan       459.5  134.0    0.0   619.249092  317.325733
Northern Victoria           724.0    0.0    0.0  3355.463415    0.000000
South-Eastern Metropolitan  630.5  240.0  199.0   664.306701  212.160000
Southern Metropolitan       586.0  246.0    0.0   569.643881  278.858824
Western Metropolitan        531.0  198.0   62.0   507.883406  244.560669
Western Victoria            599.5    0.0    0.0   655.500000    0.000000


Type                                 u
Regionname
Eastern Metropolitan        330.444444
Eastern Victoria            295.333333
Northern Metropolitan       495.026538
Northern Victoria             0.000000
South-Eastern Metropolitan  357.864865
Southern Metropolitan       466.380245
Western Metropolitan        557.637232
Western Victoria              0.000000

In [34]:
melb_df.pivot_table(
    values='Price',
    index=['Method','Type'],
    columns='Regionname',
    aggfunc='median',
    fill_value=0
)

Regionname   Eastern Metropolitan  Eastern Victoria  Northern Metropolitan  \
Method Type
PI     h                1244000.0          780000.0               900000.0
       t                 760000.0               0.0               632500.0
       u                 650000.0               0.0               410000.0
S      h                1127000.0          675000.0               920000.0
       t                 828000.0               0.0               750000.0
       u                 645750.0          492000.0               525500.0
SA     h                 932500.0          950000.0               817500.0
       t                 807500.0               0.0               425000.0
       u                      0.0               0.0               616000.0
SP     h                1050000.0          672500.0               900000.0
       t                 910000.0               0.0               690000.0
       u                 515000.0          400000.0               470000.0
VB     h                1100000.0          712500.0              1050000.0
       t                 892500.0               0.0               640000.0
       u                 500000.0               0.0               450000.0

Regionname   Northern Victoria  South-Eastern Metropolitan  \
Method Type
PI     h              500000.0                    865000.0
       t                   0.0                   1190000.0
       u                   0.0                    525000.0
S      h              555000.0                    883300.0
       t                   0.0                    875000.0
       u                   0.0                    606000.0
SA     h              540000.0                    880000.0
       t                   0.0                         0.0
       u                   0.0                         0.0
SP     h              521000.0                    770000.0
       t                   0.0                    800000.0
       u                   0.0                    601000.0
VB     h              690000.0                    850000.0
       t                   0.0                         0.0
       u                   0.0                    700000.0

Regionname   Southern Metropolitan  Western Metropolitan  Western Victoria
Method Type
PI     h                 1725000.0              870000.0          630000.0
       t                 1055000.0              670000.0               0.0
       u                  571250.0              360000.0               0.0
S      h                 1611000.0              870000.0          397500.0
       t                 1135000.0              729000.0               0.0
       u                  655000.0              489000.0               0.0
SA     h                 1390000.0              772500.0               0.0
       t                 1141000.0              467500.0               0.0
       u                  580000.0              571000.0               0.0
SP     h                 1521750.0              865000.0          360000.0
       t                 1162500.0              702500.0               0.0
       u                  550000.0              460000.0               0.0
VB     h                 1800000.0              880000.0               0.0
       t                 1250000.0              689500.0               0.0
       u                  500000.0              420000.0               0.0

In [36]:
pivot = melb_df.pivot_table(
    values='Landsize',
    index='Regionname',
    columns='Type',
    aggfunc=['median', 'mean'],
    fill_value=0
)

In [37]:
pivot.columns

MultiIndex([('median', 'h'),
            ('median', 't'),
            ('median', 'u'),
            (  'mean', 'h'),
            (  'mean', 't'),
            (  'mean', 'u')],
           names=[None, 'Type'])

In [39]:
display(pivot['mean']['u'])

Regionname
Eastern Metropolitan          330.444444
Eastern Victoria              295.333333
Northern Metropolitan         495.026538
Northern Victoria               0.000000
South-Eastern Metropolitan    357.864865
Southern Metropolitan         466.380245
Western Metropolitan          557.637232
Western Victoria                0.000000
Name: u, dtype: float64

In [40]:
mask = pivot['mean']['h'] < pivot['median']['h']
filtered_pivot = pivot[mask]
display(filtered_pivot)

                      median                     mean
Type                       h      t     u           h           t           u
Regionname
Southern Metropolitan  586.0  246.0   0.0  569.643881  278.858824  466.380245
Western Metropolitan   531.0  198.0  62.0  507.883406  244.560669  557.637232

In [41]:
print(list(filtered_pivot.index))
# ['Southern Metropolitan', 'Western Metropolitan']

['Southern Metropolitan', 'Western Metropolitan']

In [42]:
import numpy as np
mser = pd.Series(
    np.random.rand(8),
	index=[['white','white','white','blue','blue','red','red','red'], 
           ['up','down','right','up','down','up','down','left']])
display(mser)

white  up       0.003999
       down     0.558890
       right    0.941205
blue   up       0.659962
       down     0.580206
red    up       0.960867
       down     0.230802
       left     0.069761
dtype: float64

In [8]:
import pandas as pd

ratings1 = pd.read_csv('data/ratings1.csv')
ratings2 = pd.read_csv('data/ratings2.csv')
dates = pd.read_csv('data/dates.csv')
movies = pd.read_csv('data/movies.csv')

In [9]:
import pandas as pd

# Склеиваем таблицы с рейтингами
ratings = pd.concat([ratings1, ratings2], ignore_index=True)

# Добавляем столбец с датой
ratings = pd.concat([ratings, dates], axis=1)

# Присоединяем информацию о фильмах
movies_ratings = ratings.merge(movies, on='movieId', how='left')

# Выводим первые строки итоговой таблицы
movies_ratings.head()

,userId,movieId,rating,date,title,genres
0,1,1,4.0,2000-07-30 18:45:03,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,2000-07-30 18:20:47,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,2000-07-30 18:37:04,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,2000-07-30 19:03:35,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,2000-07-30 18:48:51,"Usual Suspects, The (1995)",Crime|Mystery|Thriller

In [10]:
movies['title'].nunique()

9737

In [11]:
ratings1['userId'].nunique()

274

In [12]:
dates['date'] = pd.to_datetime(dates['date'])

dates['year'] = dates['date'].dt.year

dates['year'].value_counts().idxmax()

np.int32(2000)

In [13]:
ratings = pd.concat([ratings1, ratings2])
display(ratings)

       userId  movieId  rating
0           1        1     4.0
1           1        3     4.0
2           1        6     4.0
3           1       47     5.0
4           1       50     5.0
...       ...      ...     ...
60831     610   166534     4.0
60832     610   168248     5.0
60833     610   168250     5.0
60834     610   168252     5.0
60835     610   170875     3.0

[100837 rows x 3 columns]

In [14]:
ratings = pd.concat(
    [ratings1, ratings2],
    ignore_index=True
)
display(ratings)

        userId  movieId  rating
0            1        1     4.0
1            1        3     4.0
2            1        6     4.0
3            1       47     5.0
4            1       50     5.0
...        ...      ...     ...
100832     610   166534     4.0
100833     610   168248     5.0
100834     610   168250     5.0
100835     610   168252     5.0
100836     610   170875     3.0

[100837 rows x 3 columns]

In [15]:
print('Число строк в таблице ratings: ', ratings.shape[0])
print('Число строк в таблице dates: ', dates.shape[0])
print(ratings.shape[0] == dates.shape[0])

Число строк в таблице ratings:  100837
Число строк в таблице dates:  100836
False

In [16]:
display(ratings1.tail(1))
display(ratings2.head(1))

       userId  movieId  rating
40000     274     5621     2.0

   userId  movieId  rating
0     274     5621     2.0

In [17]:
ratings = ratings.drop_duplicates(ignore_index=True)
print('Число строк в таблице ratings: ', ratings.shape[0])

Число строк в таблице ratings:  100836

In [18]:
ratings_dates = pd.concat([ratings, dates], axis=1)
display(ratings_dates.tail(7))

        userId  movieId  rating                date  year
100829     610   164179     5.0 2017-05-03 21:07:11  2017
100830     610   166528     4.0 2017-05-04 06:29:25  2017
100831     610   166534     4.0 2017-05-03 21:53:22  2017
100832     610   168248     5.0 2017-05-03 22:21:31  2017
100833     610   168250     5.0 2017-05-08 19:50:47  2017
100834     610   168252     5.0 2017-05-03 21:19:12  2017
100835     610   170875     3.0 2017-05-03 21:20:15  2017

In [19]:
joined_false = ratings_dates.join(
    movies,
    rsuffix='_right',
    how='left'
)
display(joined_false)

,userId,movieId,rating,date,year,movieId_right,title,genres
0,1,1,4.0,2000-07-30 18:45:03,2000,1.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,2000-07-30 18:20:47,2000,2.0,Jumanji (1995),Adventure|Children|Fantasy
2,1,6,4.0,2000-07-30 18:37:04,2000,3.0,Grumpier Old Men (1995),Comedy|Romance
3,1,47,5.0,2000-07-30 19:03:35,2000,4.0,Waiting to Exhale (1995),Comedy|Drama|Romance
4,1,50,5.0,2000-07-30 18:48:51,2000,5.0,Father of the Bride Part II (1995),Comedy
...,...,...,...,...,...,...,...,...
100831,610,166534,4.0,2017-05-03 21:53:22,2017,NaN,NaN,NaN
100832,610,168248,5.0,2017-05-03 22:21:31,2017,NaN,NaN,NaN
100833,610,168250,5.0,2017-05-08 19:50:47,2017,NaN,NaN,NaN
100834,610,168252,5.0,2017-05-03 21:19:12,2017,NaN,NaN,NaN
100835,610,170875,3.0,2017-05-03 21:20:15,2017,NaN,NaN,NaN

In [20]:
joined = ratings_dates.join(
    movies.set_index('movieId'),
    on='movieId',
    how='left'
)
display(joined.head())

,userId,movieId,rating,date,year,title,genres
0,1,1,4.0,2000-07-30 18:45:03,2000,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,2000-07-30 18:20:47,2000,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,2000-07-30 18:37:04,2000,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,2000-07-30 19:03:35,2000,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,2000-07-30 18:48:51,2000,"Usual Suspects, The (1995)",Crime|Mystery|Thriller

In [21]:
merged = ratings_dates.merge(
    movies,
    on='movieId',
    how='left'
)
display(merged.head())

,userId,movieId,rating,date,year,title,genres
0,1,1,4.0,2000-07-30 18:45:03,2000,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,2000-07-30 18:20:47,2000,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,2000-07-30 18:37:04,2000,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,2000-07-30 19:03:35,2000,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,2000-07-30 18:48:51,2000,"Usual Suspects, The (1995)",Crime|Mystery|Thriller

In [22]:
print('Число строк в таблице ratings_dates: ', ratings_dates.shape[0])
print('Число строк в таблице merged: ', merged.shape[0])
print(ratings_dates.shape[0] == merged.shape[0])

Число строк в таблице ratings_dates:  100836
Число строк в таблице merged:  100836
True

In [23]:
merged2 = ratings_dates.merge(
    movies,
    on='movieId',
    how='outer'
)
print('Число строк в таблице merged2: ', merged2.shape[0])
display(merged2.tail())

Число строк в таблице merged2:  100854

,userId,movieId,rating,date,year,title,genres
100849,184.0,193581,4.0,2018-09-16 14:44:42,2018.0,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
100850,184.0,193583,3.5,2018-09-16 14:52:25,2018.0,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
100851,184.0,193585,3.5,2018-09-16 14:56:45,2018.0,Flint (2017),Drama
100852,184.0,193587,3.5,2018-09-16 15:00:21,2018.0,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
100853,331.0,193609,4.0,2018-09-17 04:13:26,2018.0,Andrew Dice Clay: Dice Rules (1991),Comedy

In [24]:
merge_ratings = ratings1.merge(ratings2, how='outer')
print('Число строк в таблице merge_ratings: ', merge_ratings.shape[0])
display(merge_ratings)

Число строк в таблице merge_ratings:  100836

        userId  movieId  rating
0            1        1     4.0
1            1        3     4.0
2            1        6     4.0
3            1       47     5.0
4            1       50     5.0
...        ...      ...     ...
100831     610   166534     4.0
100832     610   168248     5.0
100833     610   168250     5.0
100834     610   168252     5.0
100835     610   170875     3.0

[100836 rows x 3 columns]

In [25]:
data_1 = pd.DataFrame({'Value': [100, 45, 80],
                       'Group': [1, 4, 5]},
                      index = ['I0', 'I1', 'I2']
                     )

In [26]:
data_2 = pd.DataFrame({'Company': ['Google', 'Amazon', 'Facebook'],
                       'Add': ['S0', 'S1', 'S7']},
                      index = ['I0', 'I1', 'I3']
                     )

In [28]:
data_1.join(data_2, how='inner')

    Value  Group Company Add
I0    100      1  Google  S0
I1     45      4  Amazon  S1

In [30]:
a = pd.DataFrame({'A': ['a', 'b', 'c'], 'B': [103, 214, 124], 'C': [1, 4, 2]})

In [29]:
b = pd.DataFrame({'V': ['d', 'b', 'c'], 'U': [1393.7, 9382.2, 1904.5], 'C': [1, 3, 2]})

In [35]:
a.merge(b, how='right', on='C')

     A      B  C  V       U
0    a  103.0  1  d  1393.7
1  NaN    NaN  3  b  9382.2
2    c  124.0  2  c  1904.5

In [36]:
import re 
def get_year_release(arg):
    #находим все слова по шаблону "(DDDD)"
    candidates = re.findall(r'\(\d{4}\)', arg) 
    # проверяем число вхождений
    if len(candidates) > 0:
        #если число вхождений больше 0,
	#очищаем строку от знаков "(" и ")"
        year = candidates[0].replace('(', '')
        year = year.replace(')', '')
        return int(year)
    else:
        #если год не указан, возвращаем None
        return None

In [37]:
movies['year_release'] = movies['title'].str.extract(r'\((\d{4})\)')
movies['year_release'].isna().sum()

np.int64(13)

In [38]:
movies['year_release'] = movies['title'].str.extract(r'\((\d{4})\)$')

ratings_movies = ratings.merge(movies, on='movieId', how='left')

movie_1999 = ratings_movies[ratings_movies['year_release'] == '1999']

movie_1999.groupby('title')['rating'].mean().sort_values().index[0]

'Bloodsport: The Dark Kumite (1999)'

In [39]:
movies['year_release'] = movies['title'].str.extract(r'\((\d{4})\)$')

ratings_movies = ratings.merge(movies, on='movieId', how='left')

movies_2010 = ratings_movies[ratings_movies['year_release'] == '2010']

movies_2010.groupby('genres')['rating'].mean().sort_values().index[0]

'Action|Sci-Fi'

In [40]:
ratings_movies = ratings.merge(movies, on='movieId', how='left')

ratings_movies.groupby('userId')['genres'].nunique().sort_values(ascending=False).index[0]

np.int64(599)

In [41]:
users_stat = ratings.groupby('userId')['rating'].agg(['count', 'mean'])

users_stat.sort_values(by=['count', 'mean'], ascending=[True, False]).index[0]

np.int64(53)

In [44]:
movies['year_release'] = movies['title'].str.extract(r'\((\d{4})\)')
ratings_movies = ratings.merge(movies, on='movieId', how='left')
movies_2018 = ratings_movies[ratings_movies['year_release'] == '2018']
genres_start = movies_2018.groupby('genres')['rating'].agg(['mean', 'count'])
genres_start = genres_start[genres_start['count'] >= 10]
genres_start.sort_values(by='mean', ascending=False).index[0]

'Action|Adventure|Sci-Fi'

In [45]:
ratings_movies['date'] = pd.to_datetime(ratings_movies['date'])

ratings_movies['year_rating'] = ratings_movies['date'].dt.year

pivot = ratings_movies.pivot_table(
    values='rating',
    index='genres',
    columns='year_rating',
    aggfunc='mean'
)

pivot

KeyError: 'date'

In [46]:
ratings = pd.concat([ratings1, ratings2], ignore_index=True)

ratings = pd.concat([ratings, dates], axis=1)

In [47]:
ratings_movies = ratings.merge(movies, on='movieId', how='left')

In [48]:
ratings_movies['date'] = pd.to_datetime(ratings_movies['date'])

ratings_movies['year_rating'] = ratings_movies['date'].dt.year

pivot = ratings_movies.pivot_table(
    values='rating',
    index='genres',
    columns='year_rating',
    aggfunc='mean'
)

pivot

year_rating,1996.0,1997.0,1998.0,1999.0,2000.0,2001.0,2002.0,2003.0,2004.0,2005.0,...,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0
genres,,,,,,,,,,,,,,,,,,,,,
(no genres listed),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,3.222222,3.656250
Action,2.720000,3.500000,NaN,NaN,2.638889,2.916667,2.625000,4.250000,2.250000,3.291667,...,3.500000,3.500000,4.500000,2.625000,2.500000,4.500000,2.750000,3.115385,2.961538,2.406250
Action|Adventure,3.500000,4.050000,4.75,4.0,3.761194,3.454545,4.083333,3.352941,4.166667,3.416667,...,3.700000,3.388889,4.000000,3.900000,4.000000,3.857143,3.539474,3.674419,3.401786,3.630952
Action|Adventure|Animation,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3.000000,4.000000,3.687500,3.458333,3.678571
Action|Adventure|Animation|Children,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4.000000,3.000000,3.500000,3.666667,3.714286,3.428571,3.187500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sci-Fi|Thriller,3.000000,3.400000,NaN,4.0,2.142857,2.500000,3.500000,3.142857,NaN,2.875000,...,4.000000,2.500000,2.666667,3.333333,4.000000,NaN,3.875000,3.800000,3.450000,3.687500
Sci-Fi|Thriller|IMAX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3.750000,4.000000,NaN,4.000000,3.666667,2.500000,NaN
Thriller,3.846154,3.857143,3.80,3.7,3.116667,3.500000,3.528571,3.239130,3.285714,3.294118,...,3.000000,3.333333,4.333333,3.000000,3.642857,3.857143,2.964286,3.302632,3.244186,3.293103
War,NaN,NaN,NaN,4.5,3.000000,3.000000,4.000000,NaN,3.000000,3.000000,...,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Western,3.166667,3.000000,NaN,4.0,4.050000,3.142857,3.000000,3.625000,4.000000,4.111111,...,3.333333,4.000000,4.100000,4.000000,NaN,3.500000,3.750000,4.050000,3.111111,3.714286

In [49]:
orders_products = orders.merge(
    products,
    on='product_id',
    how='left'
)

NameError: name 'orders' is not defined

In [63]:
import pandas as pd

orders = pd.read_csv('orders.csv')
products = pd.read_csv('products.csv')

orders_products = orders.merge(
    products,
    on='ID товара',
    how='left'
)

orders_products

FileNotFoundError: [Errno 2] No such file or directory: 'orders.csv'

In [57]:
import os

print(os.getcwd())
print(os.listdir())

/Users/emiliaalieva/IDE/Skillfactory/PY_10_Введение в Pandas
['введение.ipynb', '12.ipynb', '.venv', 'data']

In [58]:
orders = pd.read_csv('data/orders.csv')
products = pd.read_csv('data/products.csv')

ParserError: Error tokenizing data. C error: Expected 1 fields in line 7, saw 2

In [59]:
products = pd.read_csv('data/products.csv', sep=';')

In [60]:
orders = pd.read_csv('data/orders.csv', sep=';')

In [61]:
orders_products = orders.merge(
    products,
    on='ID товара',
    how='left'
)

orders_products

KeyError: 'ID товара'

In [62]:
orders_products = orders.merge(
    products,
    on='Product_ID',
    how='left'
)

KeyError: 'Product_ID'

In [65]:
paid_orders = orders_products[orders_products['Оплачен'] == 'Да']

paid_orders['profit'] = (
    paid_orders['Количество'] * paid_orders['Price']
)

paid_orders.groupby('ID Покупателя')['profit'] \
    .sum() \
    .sort_values(ascending=False) \
    .index[0]

NameError: name 'orders_products' is not defined